import type { Metadata } from "next";
import { sourceCodePro400, inter } from "@/styles/fonts";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${sourceCodePro400.className}`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
